Fix tests by adding spring-web dependency with test scope.
Tests were failing with 'java.lang.NoClassDefFoundError:
org/springframework/http/MediaType'. Not sure of the cause, but the
symptom was masked by JPAR-72.